# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "DNB Hugo Simple"
license = "MIT"
licenselink = "https://github.com/davidsneighbour/dnb-hugo-simple/blob/master/LICENSE"
description = "A simple theme for Hugo"
homepage = "https://davids-neighbour.com/"
tags = ["hugo", "simple", "white", "bootstrap4"]
features = []
min_version = "0.57.1"

[author]
  name = "Patrick Kollitsch"
  homepage = "https://davids-neighbour.com/"
